#!/bin/bash

if [ $# -eq 0 ]
    then
        echo "Error. Please make sure you've indicated correct parameters";
elif [ $1 == "prod" ]
    then
        if [[ -z $2 ]]
            then
                echo "Running dry-run"
                rsync --dry-run -az --force --delete --progress --exclude-from="rsync_exclude.txt" --include="*" -e "ssh -p22" ./ root@64.225.39.136:/var/www/html/wp-content/themes/maproulette
    elif [ $2 == "go" ]
        then
            echo "Running actual deploy"
            rsync -az --force --delete --progress --exclude-from="rsync_exclude.txt" --include="*" -e "ssh -p22" ./ root@64.225.39.136:/var/www/html/wp-content/themes/maproulette
    else
        echo "Error. Please make sure you've indicated correct parameters";
    fi
fi
